add less_5
86svg/test_guru pull request #5
Opened 2024-06-27 20:03 UTC by 86svg

2024-06-28 04:56 UTC, VidgarVii requested changes

2024-06-28 04:56 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :test
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2024-06-28 04:56 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :test
если чего-то много, то пишут это во множественном числе.

2024-06-28 04:56 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2024-06-28 04:56 UTC, VidgarVii commented on app/models/test.rb
>      joins('JOIN categories ON categories.id = tests.category_id')
тут можно упростить аргумент метода joins

2024-06-28 04:56 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where(level: level)
по ТЗ метод должен не это возвращать.

2024-06-28 13:14 UTC, VidgarVii requested changes

2024-06-28 13:14 UTC, VidgarVii commented on app/models/test.rb
>    def self.sorted_tests_by_category(category)
тут отступа не хватает, чтобы отделить код метода от ассоциаций

2024-06-28 13:14 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN test_passings ON test_passings.test_id = tests.id')
есть целая ассоциация, которая возвращает пройденные тесты. Стоит её тут использовать

2024-06-28 13:14 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :test_passings, dependent: :destroy
при has_many through достаточно 1 раз указать dependent

2024-06-29 19:49 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :category
вот эта ассоциация в схеме указана не верно

2024-06-29 19:49 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins(:test_passings)
тут join вообще не нужен. Ранее я уже писал, что есть ассоциация, которая вернёт нужные тесты. Лучше ей воспользоваться

2024-07-01 20:29 UTC, merged

2024-07-01 20:34 UTC, knmrftw commented on app/models/user.rb
> +    tests.where(level: level)
Крутой!